### ISSUE TITLE
Doesn't seem to correctly match some popular user agents

### ISSUE THREAD

**Issue by adamgotterer** [biola/Voight-Kampff#1]
`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` returns nil for human?

Latest chrome build - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31` returns false for human?

A bunch of other common agents returned false or nil when true was expected.

I'm using the latest user agent file

**Comment by mhuggins** [comment]
+1, another example from [here](https://support.google.com/webmasters/answer/1061943?hl=en):

> Googlebot/2.1 (+http://www.google.com/bot.html)

Great implementation, but would like to know that bots are correctly being matched.

**Comment by joshuap** [comment]
Does anyone have additions to their `user_agents.yml` file they can share as a gist in the meantime? :)

**Comment by adamcrown** [comment]
Sorry it took me so very long, but I finally have a rewrite of the gem ready to go with a [new user agent list](https://github.com/monperrus/crawler-user-agents) that is open and hosted on Github, so it should be easy to fork it and keep it up to date.

Check out PR #16.
