### ISSUE TITLE
Unnecessary require 'active_record' in engine.rb

### ISSUE THREAD

**Issue by twajjo** [biola/Voight-Kampff#10]
It looks like the 

require 'active_record'

statement in engine.rb is unnecessary. For rails 4.1.X implementations that don't use active_record (we use Mongo with no relational DB at all on our front-end), it causes rspec tests to hurl when they are run because rspec is trying to load active_record fixtures. For a description of this problem see:
http://stackoverflow.com/questions/25104963/rails-4-1-0-and-rspec-not-working-when-no-activerecord 

We commented out the require in our local gem copy of engine.rb and the specs ran just fine.

Thanks,
Jeff

**Comment by adamcrown** [comment]
Just released 0.2.2 without the active_record require. Thanks for pointing this out.

**Comment by twajjo** [comment]
Sorry, left my reply on another fix.

Thanks for writing Voight-Kampff. It came in really handy at Oppenheimer funds for determining crawlers in our SEO work.

**Comment by adamcrown** [comment]
Glad it could help you out. I'm hoping to get it linked up with a more up-to-date list of bots soon.
