### ISSUE TITLE
Remove dependency on HTTPClient?

### ISSUE THREAD

**Issue by joshuap** [biola/Voight-Kampff#15]
It seems like HTTPClient is being used in only [one class](https://github.com/biola/Voight-Kampff/blob/master/lib/voight_kampff/user_agents_parser.rb#L13). Is there any reason not to use net/http to avoid adding *another* http client dependency, and if so, would you be open to a pull request?

**Comment by adamcrown** [comment]
Very true. I wrote this a long time ago and it really needs some updating. I hope to have some time to give it attention soon. This should be an easy thing to fix.

**Comment by duleorlovic** [comment]
Using `derailed bundle:mem` from [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) I found that memory used at required time is:
~~~
voight_kampff: 34.4023 MiB
  voight_kampff/user_agents_parser: 27.1016 MiB
      httpclient: 26.0586 MiB
  voight_kampff/engine: 5.2305 MiB
...
~~~

which is too much compared to core gems:
~~~
 rails/all: 22.835 MiB
    rails: 12.207 MiB
      active_support: 6.4414 MiB
~~~

**Comment by adamcrown** [comment]
I've just finished a rewrite of this gem (#16). It no longer depends on HTTPClient and is less dependent on Rails.

The memory usage should be much lower now as well.
