### ISSUE TITLE
Not compatible with rails 4.1.x

### ISSUE THREAD

**Issue by halloffame** [biola/Voight-Kampff#23]
Hey Adam, is there a reason you require rack to be `~> 1.6`. The problem is that `actionpack 4.1.14` depends on `rack ~> 1.5.2`. What is the minimum version rack can be for Voight-Kampff to work?

**Comment by adamcrown** [comment]
I don't think there was any specific reason. I think that was just the only thing I had tested it with recently. I don't see any reason that Rack 1.5 wouldn't work. I would just try it out and run the test suite to make sure there are no errors.

**Comment by noctivityinc** [comment]
Adam - 

Im running a Rails 3.2.22 app that uses rack 1.4.7.  Is there a reason it shouldnt work with that version of rack?  Right now I can't install the gem due to the 1.5 dependency.

**Comment by adamcrown** [comment]
I don't know of any reason it wouldn't work on Rack 1.4 so I went ahead and lowered the required version. I'm certainly not guaranteeing it will work on Rails 3 though. If you run into any problems, let me know and I'll see what I can do.
