### ISSUE TITLE
Why is "Googlebot" not recognized without trailing slash?

### ISSUE THREAD

**Issue by egilburg** [biola/Voight-Kampff#27]
https://support.google.com/webmasters/answer/182072 says `Googlebot` is used as user agent for the default web crawler. 

But https://github.com/biola/Voight-Kampff/blob/master/config/crawler-user-agents.json#L3 only recognizes `Googlebot/` with trailing slash.

Thanks.

**Comment by adamcrown** [comment]
Honestly, I'm not sure why. I'm no expert in SEO or user agents.

This project uses the user agent data hosted at [monperrus/crawler-user-agents](https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json), and you'll notice they specifically add a trailing slash to their entry for Googlebot. I'd open an issue there to ask about this. If you can get things fixed there, then we can update the bot list here.
