### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by pomartel** [biola/Voight-Kampff#28]
Voight-Kampff depends on rack ~> 1.0.4 which is incompatible with Rails 5 (rack ~> 2.0).

Is there a reason why this dependency exists or could it be bumped to 2.0?

**Comment by MSeneadza** [comment]
I was wondering the same thing

**Comment by adamcrown** [comment]
That requirement was from before Rack 2.0 when nobody knew how compatible it would be with the 1.* series. I've loosened the requirement and pushed up version 1.1.0. Thanks for reporting this.
