### ISSUE TITLE
Match other bots which are not in the list

### ISSUE THREAD

**Issue by printercu** [biola/Voight-Kampff#29]
Hi!

WDYT about adding `/bot/` regexp to the end of config json? This way most of bots which are not listed in it will still be detected. I'm not sure, but it also seems like some bots which don't have `bot` should match `\+https?://`, as they have link to their description. I haven't seen such links browsers agent strings.

**Comment by adamcrown** [comment]
Thanks for the suggestion @printercu, but I'd prefer to keep the actual bot-matching to https://github.com/monperrus/crawler-user-agents, and just handle the integration with Rack/Rails as part of this project.
