### ISSUE TITLE
Encoding Error & Failed Read Handling

### ISSUE THREAD

**Issue by richseviora** [biola/Voight-Kampff#33]
My client is receiving encoding errors when the `voight_kampff:import_user_agents` task is executed.

This appears to be due to the following entry's description:
```json
  {
    "pattern": "BTWebClient",
    "addition_date": "2018/06/27",
    "instances": [
      "BTWebClient/180B(9704)"
    ],
    "url": "http://www.utorrent.com/",
    "description": "µTorrent BitTorrent Client"
  },
```
The `µ` character is causing the write to fail b/c the contents are being captured as `Encoding::ASCII_8BIT` not `Encoding::UTF_8` as the response header would indicate.

**Edit**: 
As @Djmill notes, if the `get` call fails then we end up writing an empty string to the file which breaks this gem.

**Comment by jmeattle** [comment]
PR that introduces the issue:
https://github.com/monperrus/crawler-user-agents/pull/115/files#diff-df799e9f8ab7875b5e90cd4ed9e04de2R2674

**Comment by Djmill** [comment]
I've also been seeing this within the last day in prod and locally, which caused me to open https://github.com/biola/Voight-Kampff/issues/35 as a side-effect to this behavior.

Without any error handling here, the file is overwritten with an empty file. If you run a daily job to fetch changes, this may break your application anywhere you use `.bot?`.

#35

**Comment by richseviora** [comment]
@Djmill I agree that we should write some error handling in there! I'm wondering whether we should be abort the task if the request had failed, or just output a warning.

**Comment by Djmill** [comment]
@richseviora  good point, a warning along with a failed task might work well. At least that way if anyone somehow misses the warning in their logs, they'll should see that the task failed and then read up the stack trace.

**Comment by adamcrown** [comment]
I merged this PR https://github.com/biola/Voight-Kampff/pull/34, which should fix the issue. Thanks @ richseviora!
