### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by twajjo** [biola/Voight-Kampff#9]
I have three things I'd like to contribute, if I may:
1. I'd like to make @description in VoightKampff::Test accessible or at least readable. I'd like to log the "pretty" name of the 'bot user agent when I find a match.
2. I'd like to change VoightKampff::Test#load_agents to allow the user_agents.yml found in Rails.root/config extend the list found in VoightKampff.root/config/user_agents.yml rather than stomp over it. This would allow me to use the (perfectly good) list you provide plus add some local extensions for marketing firm we've hired to crawl our site for SEO.
3. I'd like the ability to add a "one shot deal" for testing to the @@agents list. I guess this would be a class method on Test that could be used to add single instances of crawlers from a chunk of test code. The addition would exist only as long as the instance (in this case a Rails app) ran and only for test purposes.  Something like add_agent(opts) with the opts having :string, :description, and the other pieces-parts that define an agent to add to the @@agents list.

**Comment by adamcrown** [comment]
Sorry it's taken me a while to respond to this. This all sounds good to me. If you'd like to send a pull request I'd be happy to merge it if the implementation is clean.

**Comment by twajjo** [comment]
I'm a bit swamped right now, but I'll try to find some time soon to put in the feature. It's pretty simple.
Thanks.

**Comment by adamcrown** [comment]
There hasn't been anything happening with this is quite a while now plus I think version 1.0 would change a few of these requirements. So I'm going to close this issue. If there are any specific features you'd still like added, just create new issues for them. Thanks.
